version: '3.8'

services:
  db:
    image: postgres:14.15-alpine
    container_name: postgres_container
    #command: bash -c "rm -rf var/lib/postgresql/data/*"
    environment:
      POSTGRES_DB: enquestas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql@14/data:rw
    ports:
      - "5432:5432"
    networks:
      - db-network

  frontend:
    image: httpd:latest
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /frontend:/usr/local/apache2/htdocs
    networks:
      - db-network

  filebrowser:
    container_name: filebrowser
    ports:
      - "8081:8080"
    volumes:
      - /frontend:/data
      - /frontend/filebrowser:/config
    environment:
      - FB_BASEURL=/f
    image: hurlenko/filebrowser
    restart: always
    networks:
      - db-network

  backend:
    container_name: backend
    build:
      context: ./enquestes
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    volumes:
      - ./enquestes:/var/www/html
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
